## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=50G
#$ -N run_saige
#$ -o stdout_run_saige_B
#$ -e stderr_run_saige_B
#$ -t 1-2510

i=${SGE_TASK_ID};

gene_name=$(sed "${i}q;d" gene_name.txt)

R_PATH=/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/RSAIGE/bin/

cd /share/ScratchGeneral/anncuo/software/qtl/extdata

${R_PATH}/Rscript step1_fitNULLGLMM_qtl.R \
        --useSparseGRMtoFitNULL=FALSE  \
        --useGRMtoFitNULL=FALSE \
        --phenoFile=/share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/input/Sept23/SCT/CD4_NC_sc_pheno_cov_1pct_subset.tsv	\
        --phenoCol=$gene_name       \
        --covarColList=age,sex,pc1,pc2,pc3,pc4,pc5,pc6,pf1,pf2    \
        --sampleCovarColList=age,sex,pc1,pc2,pc3,pc4,pc5,pc6      \
        --sampleIDColinphenoFile=individual \
        --traitType=count \
        --outputPrefix=/directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/output/subsets/${gene_name}_1pct_CD4_NC_poisson_test \
        --skipVarianceRatioEstimation=FALSE  \
        --isRemoveZerosinPheno=FALSE \
        --isCovariateOffset=FALSE  \
        --isCovariateTransform=TRUE  \
        --skipModelFitting=FALSE  \
        --tol=0.00001   \
        --plinkFile=/share/ScratchGeneral/anncuo/OneK1K/plink_files/plink_pruning/chr2_pruned_sc_samples       \
        --IsOverwriteVarianceRatioFile=TRUE &> /directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/output/subsets/${gene_name}_1pct_CD4_NC_poisson_test_`date +%Y-%m-%d.%H:%M:%S`.log


${R_PATH}/Rscript step2_tests_qtl.R       \
        --bedFile=./input/n.indep_100_n.cell_1.bed      \
        --bimFile=./input/n.indep_100_n.cell_1.bim      \
        --famFile=./input/n.indep_100_n.cell_1.fam      \
        --SAIGEOutputFile=${step2prefix}     \
        --chrom=2       \
        --minMAF=0 \
        --minMAC=20 \
        --LOCO=FALSE    \
        --GMMATmodelFile=${step1prefix}.rda     \
        --SPAcutoff=2 \
        --varianceRatioFile=${step1prefix}.varianceRatio.txt    \
        --rangestoIncludeFile=${regionFile}     \
        --markers_per_chunk=10000



singularity exec --bind /directflow,/share /share/ScratchGeneral/anncuo/saige_qtl/SAIGE-QTL.sif.4 Rscript /usr/local/bin/step2_tests_qtl.R	 \
        --bedFile=/share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/input/B_IN/${gene_name}_1000000bp.bed  \
        --bimFile=/share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/input/B_IN/${gene_name}_1000000bp.bim  \
        --famFile=/share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/input/B_IN/${gene_name}_1000000bp.fam  \
        --AlleleOrder=alt-first \
        --SAIGEOutputFile=/share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/output/results/1000000bp/${gene_name}_B_IN.txt  \
        --chrom=22  \
        --minMAF=0  \
        --minMAC=20  \
        --LOCO=FALSE \
        --is_fastTest=TRUE      \
        --GMMATmodelFile=/share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/output/${gene_name}_B_IN_poisson_test.rda  \
        --varianceRatioFile=/share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/output/${gene_name}_B_IN_poisson_test.varianceRatio.txt  \
        --markers_per_chunk=10000  \
        --pval_cutoff_for_fastTest=0.05  \
        --SPAcutoff=10000  &>  /share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/output/${gene_name}_B_IN_poisson_single_`date +%Y-%m-%d.%H:%M:%S`.log
 
 qstat -j $JOB_ID > /share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/output/${gene_name}_B_IN_poisson_single_`date +%Y-%m-%d.%H:%M:%S`_qstat.txt
