#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -q short.q
#$ -r yes
#$ -l mem_requested=50G
#$ -N run_saige
#$ -o stdout_run_saige_CD4_NC_sub_5
#$ -e stderr_run_saige_CD4_NC_sub_5
#$ -t 1-923

# #$ -m ae
# #$ -M a.cuomo@garvan.org.au

i=${SGE_TASK_ID};
chrom=4

gene_name=$(sed "${i}q;d" /directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/input/power_analysis_subsets/gene_lists/chrom4_genes.txt)
regionFile="/directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/input/power_analysis_subsets/cis_region_files/${gene_name}_cis_region_1Mb.txt"

R_PATH=/share/ScratchGeneral/anncuo/jupyter/conda_notebooks/envs/RSAIGE/bin/

cd /share/ScratchGeneral/anncuo/software/qtl/extdata

${R_PATH}/Rscript step1_fitNULLGLMM_qtl.R \
        --useSparseGRMtoFitNULL=FALSE  \
        --useGRMtoFitNULL=FALSE \
        --phenoFile=/share/ScratchGeneral/anncuo/OneK1K/saige_eqtl/input/Sept23/SCT/CD4_NC_sc_pheno_cov_5pct_subset.tsv	\
        --phenoCol=$gene_name       \
        --covarColList=age,sex,pc1,pc2,pc3,pc4,pc5,pc6,pf1,pf2    \
        --sampleCovarColList=age,sex,pc1,pc2,pc3,pc4,pc5,pc6      \
        --sampleIDColinphenoFile=individual \
        --traitType=count \
        --outputPrefix=/directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/output/subsets/subset_5pct/${gene_name}_5pct_CD4_NC_poisson_test \
        --skipVarianceRatioEstimation=FALSE  \
        --isRemoveZerosinPheno=FALSE \
        --isCovariateOffset=FALSE  \
        --isCovariateTransform=TRUE  \
        --skipModelFitting=FALSE  \
        --tol=0.00001   \
        --plinkFile=/directflow/SCCGGroupShare/projects/anncuo/OneK1K/plink_files/plink_pruning/chr2_pruned_sc_samples       \
        --IsOverwriteVarianceRatioFile=TRUE &> /directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/output/subsets/subset_5pct/${gene_name}_5pct_CD4_NC_poisson_test_`date +%Y-%m-%d.%H:%M:%S`.log


${R_PATH}/Rscript step2_tests_qtl.R       \
        --vcfFile=/directflow/SCCGGroupShare/projects/anncuo/OneK1K/genotypes/filter_vcf_r08/chr${chrom}.dose.filtered.R2_0.8.vcf.gz  \
        --vcfFileIndex=/directflow/SCCGGroupShare/projects/anncuo/OneK1K/genotypes/filter_vcf_r08/chr${chrom}.dose.filtered.R2_0.8.vcf.gz.csi  \
        --SAIGEOutputFile=/directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/output/subsets/subset_5pct/${gene_name}_5pct_CD4_NC_poisson_test_cis     \
        --chrom=$chrom       \
        --minMAF=0 \
        --minMAC=20 \
        --LOCO=FALSE    \
        --GMMATmodelFile=/directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/output/subsets/subset_5pct/${gene_name}_5pct_CD4_NC_poisson_test.rda     \
        --SPAcutoff=2 \
        --varianceRatioFile=/directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/output/subsets/subset_5pct/${gene_name}_5pct_CD4_NC_poisson_test.varianceRatio.txt    \
        --rangestoIncludeFile=${regionFile}     \
        --markers_per_chunk=10000 &> /directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/output/subsets/subset_5pct/${gene_name}_5pct_CD4_NC_poisson_test_cis_`date +%Y-%m-%d.%H:%M:%S`.log


 qstat -j $JOB_ID > /directflow/SCCGGroupShare/projects/anncuo/OneK1K/saige_eqtl/output/subsets/subset_5pct/${gene_name}_5pct_CD4_NC_poisson_test_cis_`date +%Y-%m-%d.%H:%M:%S`_qstat.txt
